dotnet pack ./src/Bash                          -c Release -o ./../../build/Bash
dotnet pack ./src/Carbon.CI                     -c Release -o ./../../build/Carbon.CI
dotnet pack ./src/Carbon.CI.Abstractions        -c Release -o ./../../build/Carbon.CI.Abstractions
dotnet pack ./src/Carbon.Platform.Diagnostics   -c Release -o ./../../build/Carbon.Platform.Diagnostics
dotnet pack ./src/GitHub                        -c Release -o ./../../build/GitHub
dotnet pack ./src/Bitbucket                     -c Release -o ./../../build/Bitbucket
dotnet pack ./src/Carbon.Building               -c Release -o ./../../build/Carbon.Building
dotnet pack ./src/Carbon.Building.Web           -c Release -o ./../../build/Carbon.Building.Web
dotnet pack ./src/Carbon.Hosting                -c Release -o ./../../build/Carbon.Hosting
dotnet pack ./src/Carbon.Hosting.IIS            -c Release -o ./../../build/Carbon.Hosting.IIS
dotnet pack ./src/Carbon.Packaging              -c Release -o ./../../build/Carbon.Packaging
dotnet pack ./src/Carbon.Platform               -c Release -o ./../../build/Carbon.Platform
dotnet pack ./src/Carbon.Platform.Abstractions  -c Release -o ./../../build/Carbon.Platform.Abstractions
dotnet pack ./src/Carbon.Platform.Web           -c Release -o ./../../build/Carbon.Platform.Web
dotnet pack ./src/Carbon.Platform.Services      -c Release -o ./../../build/Carbon.Platform.Services
dotnet pack ./src/Carbon.Platform.Client        -c Release -o ./../../build/Carbon.Platform.Client
dotnet pack ./src/Carbon.Platform.Monitoring    -c Release -o ./../../build/Carbon.Platform.Monitoring
dotnet pack ./src/Carbon.Platform.Metrics       -c Release -o ./../../build/Carbon.Platform.Metrics
dotnet pack ./src/Carbon.VersionControl         -c Release -o ./../../build/Carbon.VersionControl
dotnet pack ./src/Carbon.Platform.Management    -c Release -o ./../../build/Carbon.Platform.Management
dotnet pack ./src/Carbon.Platform.Configuration -c Release -o ./../../build/Carbon.Platform.Configuration
dotnet pack ./src/Carbon.Kms                    -c Release -o ./../../build/Carbon.Kms
dotnet pack ./src/Carbon.Kms.Abstractions       -c Release -o ./../../build/Carbon.Kms.Abstractions